%YAML:1.0 # need to specify the file type at the top!

sys:
  verbosity: 2 # 0:ALL 1: DEBUG 2:INFO 3:WARNING 4:ERROR 5: SILENT
  save_timing: true
  path_timing: "MINS_DIR/../../../../outputs/tmp/0.time"
  save_state: true
  path_state: "MINS_DIR/../../../../outputs/tmp/"
  save_trajectory: false
  path_trajectory: "MINS_DIR/../../../../outputs/tmp/0.txt"
  save_prints: false
  exp_id: 0

  path_bag: "/media/wl/RPNG_FLASH_9/dataset/kaist/urban29.bag"
  bag_start: 0
  bag_durr: -1